services:
  - type: web
    name: strapi
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~18.20.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: massoerin-cloudinary
      - key: CLOUDINARY_KEY
        sync: 846519329162819
      - key: CLOUDINARY_SECRET
        sync: yDHOTdBeI7r4D5Ip4BCG4tPe7T4
      - key: DATABASE_URL
        value: postgresql://massoerin_postgres_user:c6Nr2NaaHRJ0DPyeupkEUTfxtWpauXvG@dpg-d0191024d50c7385k5vg-a/massoerin_postgres
      - key: JWT_SECRET
        generateValue: 1f5a0eeb27434d1f8dcfeec6c1398632
      - key: ADMIN_JWT_SECRET
        generateValue: 5f8e2dd6d8c54aeea971c9ba36d2fcd8
      - key: APP_KEYS
        generateValue: dc9f48c3e7cb486bb1faeb16ab0c537a,f3ad41eb90c84573b80d70a2d842a73b,cf01d274091c44e9a8cfcd1d70a7fdd1

